/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as GiftingRouteImport } from './routes/gifting'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BulkOrdersRouteImport } from './routes/bulk-orders'
import { Route as BuildYourKitRouteImport } from './routes/build-your-kit'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingRoute = GiftingRouteImport.update({
  id: '/gifting',
  path: '/gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOrdersRoute = BulkOrdersRouteImport.update({
  id: '/bulk-orders',
  path: '/bulk-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildYourKitRoute = BuildYourKitRouteImport.update({
  id: '/build-your-kit',
  path: '/build-your-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/build-your-kit': typeof BuildYourKitRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/contact': typeof ContactRoute
  '/gifting': typeof GiftingRoute
  '/training': typeof TrainingRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/build-your-kit': typeof BuildYourKitRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/contact': typeof ContactRoute
  '/gifting': typeof GiftingRoute
  '/training': typeof TrainingRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/build-your-kit': typeof BuildYourKitRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/contact': typeof ContactRoute
  '/gifting': typeof GiftingRoute
  '/training': typeof TrainingRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/build-your-kit'
    | '/bulk-orders'
    | '/contact'
    | '/gifting'
    | '/training'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/build-your-kit'
    | '/bulk-orders'
    | '/contact'
    | '/gifting'
    | '/training'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/build-your-kit'
    | '/bulk-orders'
    | '/contact'
    | '/gifting'
    | '/training'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuildYourKitRoute: typeof BuildYourKitRoute
  BulkOrdersRoute: typeof BulkOrdersRoute
  ContactRoute: typeof ContactRoute
  GiftingRoute: typeof GiftingRoute
  TrainingRoute: typeof TrainingRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting': {
      id: '/gifting'
      path: '/gifting'
      fullPath: '/gifting'
      preLoaderRoute: typeof GiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-orders': {
      id: '/bulk-orders'
      path: '/bulk-orders'
      fullPath: '/bulk-orders'
      preLoaderRoute: typeof BulkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-your-kit': {
      id: '/build-your-kit'
      path: '/build-your-kit'
      fullPath: '/build-your-kit'
      preLoaderRoute: typeof BuildYourKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuildYourKitRoute: BuildYourKitRoute,
  BulkOrdersRoute: BulkOrdersRoute,
  ContactRoute: ContactRoute,
  GiftingRoute: GiftingRoute,
  TrainingRoute: TrainingRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
