/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipExecutiveGiftingRouteImport } from './routes/vip-executive-gifting'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TechGiftsRouteImport } from './routes/tech-gifts'
import { Route as RewardsRecognitionRouteImport } from './routes/rewards-recognition'
import { Route as PhysicalFitnessKitRouteImport } from './routes/physical-fitness-kit'
import { Route as OfficeCarryEssentialsRouteImport } from './routes/office-carry-essentials'
import { Route as MilestoneGiftsRouteImport } from './routes/milestone-gifts'
import { Route as MeetingsConferenceEssentialsRouteImport } from './routes/meetings-conference-essentials'
import { Route as LearningWorkshopsRouteImport } from './routes/learning-workshops'
import { Route as HomeLivingRouteImport } from './routes/home-living'
import { Route as GiftingRouteImport } from './routes/gifting'
import { Route as FoodGourmetRouteImport } from './routes/food-gourmet'
import { Route as EventSeminarGiftsRouteImport } from './routes/event-seminar-gifts'
import { Route as EmployeeWelcomeKitRouteImport } from './routes/employee-welcome-kit'
import { Route as EcoFriendlyRouteImport } from './routes/eco-friendly'
import { Route as DeskEssentialsRouteImport } from './routes/desk-essentials'
import { Route as DeStressKitsRouteImport } from './routes/de-stress-kits'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BulkOrdersRouteImport } from './routes/bulk-orders'
import { Route as BuildYourKitRouteImport } from './routes/build-your-kit'
import { Route as ApparelsRouteImport } from './routes/apparels'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const VipExecutiveGiftingRoute = VipExecutiveGiftingRouteImport.update({
  id: '/vip-executive-gifting',
  path: '/vip-executive-gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TechGiftsRoute = TechGiftsRouteImport.update({
  id: '/tech-gifts',
  path: '/tech-gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRecognitionRoute = RewardsRecognitionRouteImport.update({
  id: '/rewards-recognition',
  path: '/rewards-recognition',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicalFitnessKitRoute = PhysicalFitnessKitRouteImport.update({
  id: '/physical-fitness-kit',
  path: '/physical-fitness-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeCarryEssentialsRoute = OfficeCarryEssentialsRouteImport.update({
  id: '/office-carry-essentials',
  path: '/office-carry-essentials',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestoneGiftsRoute = MilestoneGiftsRouteImport.update({
  id: '/milestone-gifts',
  path: '/milestone-gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsConferenceEssentialsRoute =
  MeetingsConferenceEssentialsRouteImport.update({
    id: '/meetings-conference-essentials',
    path: '/meetings-conference-essentials',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearningWorkshopsRoute = LearningWorkshopsRouteImport.update({
  id: '/learning-workshops',
  path: '/learning-workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLivingRoute = HomeLivingRouteImport.update({
  id: '/home-living',
  path: '/home-living',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingRoute = GiftingRouteImport.update({
  id: '/gifting',
  path: '/gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodGourmetRoute = FoodGourmetRouteImport.update({
  id: '/food-gourmet',
  path: '/food-gourmet',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSeminarGiftsRoute = EventSeminarGiftsRouteImport.update({
  id: '/event-seminar-gifts',
  path: '/event-seminar-gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeWelcomeKitRoute = EmployeeWelcomeKitRouteImport.update({
  id: '/employee-welcome-kit',
  path: '/employee-welcome-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const EcoFriendlyRoute = EcoFriendlyRouteImport.update({
  id: '/eco-friendly',
  path: '/eco-friendly',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskEssentialsRoute = DeskEssentialsRouteImport.update({
  id: '/desk-essentials',
  path: '/desk-essentials',
  getParentRoute: () => rootRouteImport,
} as any)
const DeStressKitsRoute = DeStressKitsRouteImport.update({
  id: '/de-stress-kits',
  path: '/de-stress-kits',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOrdersRoute = BulkOrdersRouteImport.update({
  id: '/bulk-orders',
  path: '/bulk-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildYourKitRoute = BuildYourKitRouteImport.update({
  id: '/build-your-kit',
  path: '/build-your-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApparelsRoute = ApparelsRouteImport.update({
  id: '/apparels',
  path: '/apparels',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apparels': typeof ApparelsRoute
  '/build-your-kit': typeof BuildYourKitRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/contact': typeof ContactRoute
  '/de-stress-kits': typeof DeStressKitsRoute
  '/desk-essentials': typeof DeskEssentialsRoute
  '/eco-friendly': typeof EcoFriendlyRoute
  '/employee-welcome-kit': typeof EmployeeWelcomeKitRoute
  '/event-seminar-gifts': typeof EventSeminarGiftsRoute
  '/food-gourmet': typeof FoodGourmetRoute
  '/gifting': typeof GiftingRoute
  '/home-living': typeof HomeLivingRoute
  '/learning-workshops': typeof LearningWorkshopsRoute
  '/meetings-conference-essentials': typeof MeetingsConferenceEssentialsRoute
  '/milestone-gifts': typeof MilestoneGiftsRoute
  '/office-carry-essentials': typeof OfficeCarryEssentialsRoute
  '/physical-fitness-kit': typeof PhysicalFitnessKitRoute
  '/rewards-recognition': typeof RewardsRecognitionRoute
  '/tech-gifts': typeof TechGiftsRoute
  '/training': typeof TrainingRoute
  '/travel': typeof TravelRoute
  '/vip-executive-gifting': typeof VipExecutiveGiftingRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apparels': typeof ApparelsRoute
  '/build-your-kit': typeof BuildYourKitRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/contact': typeof ContactRoute
  '/de-stress-kits': typeof DeStressKitsRoute
  '/desk-essentials': typeof DeskEssentialsRoute
  '/eco-friendly': typeof EcoFriendlyRoute
  '/employee-welcome-kit': typeof EmployeeWelcomeKitRoute
  '/event-seminar-gifts': typeof EventSeminarGiftsRoute
  '/food-gourmet': typeof FoodGourmetRoute
  '/gifting': typeof GiftingRoute
  '/home-living': typeof HomeLivingRoute
  '/learning-workshops': typeof LearningWorkshopsRoute
  '/meetings-conference-essentials': typeof MeetingsConferenceEssentialsRoute
  '/milestone-gifts': typeof MilestoneGiftsRoute
  '/office-carry-essentials': typeof OfficeCarryEssentialsRoute
  '/physical-fitness-kit': typeof PhysicalFitnessKitRoute
  '/rewards-recognition': typeof RewardsRecognitionRoute
  '/tech-gifts': typeof TechGiftsRoute
  '/training': typeof TrainingRoute
  '/travel': typeof TravelRoute
  '/vip-executive-gifting': typeof VipExecutiveGiftingRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apparels': typeof ApparelsRoute
  '/build-your-kit': typeof BuildYourKitRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/contact': typeof ContactRoute
  '/de-stress-kits': typeof DeStressKitsRoute
  '/desk-essentials': typeof DeskEssentialsRoute
  '/eco-friendly': typeof EcoFriendlyRoute
  '/employee-welcome-kit': typeof EmployeeWelcomeKitRoute
  '/event-seminar-gifts': typeof EventSeminarGiftsRoute
  '/food-gourmet': typeof FoodGourmetRoute
  '/gifting': typeof GiftingRoute
  '/home-living': typeof HomeLivingRoute
  '/learning-workshops': typeof LearningWorkshopsRoute
  '/meetings-conference-essentials': typeof MeetingsConferenceEssentialsRoute
  '/milestone-gifts': typeof MilestoneGiftsRoute
  '/office-carry-essentials': typeof OfficeCarryEssentialsRoute
  '/physical-fitness-kit': typeof PhysicalFitnessKitRoute
  '/rewards-recognition': typeof RewardsRecognitionRoute
  '/tech-gifts': typeof TechGiftsRoute
  '/training': typeof TrainingRoute
  '/travel': typeof TravelRoute
  '/vip-executive-gifting': typeof VipExecutiveGiftingRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apparels'
    | '/build-your-kit'
    | '/bulk-orders'
    | '/contact'
    | '/de-stress-kits'
    | '/desk-essentials'
    | '/eco-friendly'
    | '/employee-welcome-kit'
    | '/event-seminar-gifts'
    | '/food-gourmet'
    | '/gifting'
    | '/home-living'
    | '/learning-workshops'
    | '/meetings-conference-essentials'
    | '/milestone-gifts'
    | '/office-carry-essentials'
    | '/physical-fitness-kit'
    | '/rewards-recognition'
    | '/tech-gifts'
    | '/training'
    | '/travel'
    | '/vip-executive-gifting'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apparels'
    | '/build-your-kit'
    | '/bulk-orders'
    | '/contact'
    | '/de-stress-kits'
    | '/desk-essentials'
    | '/eco-friendly'
    | '/employee-welcome-kit'
    | '/event-seminar-gifts'
    | '/food-gourmet'
    | '/gifting'
    | '/home-living'
    | '/learning-workshops'
    | '/meetings-conference-essentials'
    | '/milestone-gifts'
    | '/office-carry-essentials'
    | '/physical-fitness-kit'
    | '/rewards-recognition'
    | '/tech-gifts'
    | '/training'
    | '/travel'
    | '/vip-executive-gifting'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apparels'
    | '/build-your-kit'
    | '/bulk-orders'
    | '/contact'
    | '/de-stress-kits'
    | '/desk-essentials'
    | '/eco-friendly'
    | '/employee-welcome-kit'
    | '/event-seminar-gifts'
    | '/food-gourmet'
    | '/gifting'
    | '/home-living'
    | '/learning-workshops'
    | '/meetings-conference-essentials'
    | '/milestone-gifts'
    | '/office-carry-essentials'
    | '/physical-fitness-kit'
    | '/rewards-recognition'
    | '/tech-gifts'
    | '/training'
    | '/travel'
    | '/vip-executive-gifting'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApparelsRoute: typeof ApparelsRoute
  BuildYourKitRoute: typeof BuildYourKitRoute
  BulkOrdersRoute: typeof BulkOrdersRoute
  ContactRoute: typeof ContactRoute
  DeStressKitsRoute: typeof DeStressKitsRoute
  DeskEssentialsRoute: typeof DeskEssentialsRoute
  EcoFriendlyRoute: typeof EcoFriendlyRoute
  EmployeeWelcomeKitRoute: typeof EmployeeWelcomeKitRoute
  EventSeminarGiftsRoute: typeof EventSeminarGiftsRoute
  FoodGourmetRoute: typeof FoodGourmetRoute
  GiftingRoute: typeof GiftingRoute
  HomeLivingRoute: typeof HomeLivingRoute
  LearningWorkshopsRoute: typeof LearningWorkshopsRoute
  MeetingsConferenceEssentialsRoute: typeof MeetingsConferenceEssentialsRoute
  MilestoneGiftsRoute: typeof MilestoneGiftsRoute
  OfficeCarryEssentialsRoute: typeof OfficeCarryEssentialsRoute
  PhysicalFitnessKitRoute: typeof PhysicalFitnessKitRoute
  RewardsRecognitionRoute: typeof RewardsRecognitionRoute
  TechGiftsRoute: typeof TechGiftsRoute
  TrainingRoute: typeof TrainingRoute
  TravelRoute: typeof TravelRoute
  VipExecutiveGiftingRoute: typeof VipExecutiveGiftingRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip-executive-gifting': {
      id: '/vip-executive-gifting'
      path: '/vip-executive-gifting'
      fullPath: '/vip-executive-gifting'
      preLoaderRoute: typeof VipExecutiveGiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-gifts': {
      id: '/tech-gifts'
      path: '/tech-gifts'
      fullPath: '/tech-gifts'
      preLoaderRoute: typeof TechGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards-recognition': {
      id: '/rewards-recognition'
      path: '/rewards-recognition'
      fullPath: '/rewards-recognition'
      preLoaderRoute: typeof RewardsRecognitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical-fitness-kit': {
      id: '/physical-fitness-kit'
      path: '/physical-fitness-kit'
      fullPath: '/physical-fitness-kit'
      preLoaderRoute: typeof PhysicalFitnessKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office-carry-essentials': {
      id: '/office-carry-essentials'
      path: '/office-carry-essentials'
      fullPath: '/office-carry-essentials'
      preLoaderRoute: typeof OfficeCarryEssentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestone-gifts': {
      id: '/milestone-gifts'
      path: '/milestone-gifts'
      fullPath: '/milestone-gifts'
      preLoaderRoute: typeof MilestoneGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings-conference-essentials': {
      id: '/meetings-conference-essentials'
      path: '/meetings-conference-essentials'
      fullPath: '/meetings-conference-essentials'
      preLoaderRoute: typeof MeetingsConferenceEssentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-workshops': {
      id: '/learning-workshops'
      path: '/learning-workshops'
      fullPath: '/learning-workshops'
      preLoaderRoute: typeof LearningWorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-living': {
      id: '/home-living'
      path: '/home-living'
      fullPath: '/home-living'
      preLoaderRoute: typeof HomeLivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting': {
      id: '/gifting'
      path: '/gifting'
      fullPath: '/gifting'
      preLoaderRoute: typeof GiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-gourmet': {
      id: '/food-gourmet'
      path: '/food-gourmet'
      fullPath: '/food-gourmet'
      preLoaderRoute: typeof FoodGourmetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-seminar-gifts': {
      id: '/event-seminar-gifts'
      path: '/event-seminar-gifts'
      fullPath: '/event-seminar-gifts'
      preLoaderRoute: typeof EventSeminarGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-welcome-kit': {
      id: '/employee-welcome-kit'
      path: '/employee-welcome-kit'
      fullPath: '/employee-welcome-kit'
      preLoaderRoute: typeof EmployeeWelcomeKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eco-friendly': {
      id: '/eco-friendly'
      path: '/eco-friendly'
      fullPath: '/eco-friendly'
      preLoaderRoute: typeof EcoFriendlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk-essentials': {
      id: '/desk-essentials'
      path: '/desk-essentials'
      fullPath: '/desk-essentials'
      preLoaderRoute: typeof DeskEssentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de-stress-kits': {
      id: '/de-stress-kits'
      path: '/de-stress-kits'
      fullPath: '/de-stress-kits'
      preLoaderRoute: typeof DeStressKitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-orders': {
      id: '/bulk-orders'
      path: '/bulk-orders'
      fullPath: '/bulk-orders'
      preLoaderRoute: typeof BulkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-your-kit': {
      id: '/build-your-kit'
      path: '/build-your-kit'
      fullPath: '/build-your-kit'
      preLoaderRoute: typeof BuildYourKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apparels': {
      id: '/apparels'
      path: '/apparels'
      fullPath: '/apparels'
      preLoaderRoute: typeof ApparelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApparelsRoute: ApparelsRoute,
  BuildYourKitRoute: BuildYourKitRoute,
  BulkOrdersRoute: BulkOrdersRoute,
  ContactRoute: ContactRoute,
  DeStressKitsRoute: DeStressKitsRoute,
  DeskEssentialsRoute: DeskEssentialsRoute,
  EcoFriendlyRoute: EcoFriendlyRoute,
  EmployeeWelcomeKitRoute: EmployeeWelcomeKitRoute,
  EventSeminarGiftsRoute: EventSeminarGiftsRoute,
  FoodGourmetRoute: FoodGourmetRoute,
  GiftingRoute: GiftingRoute,
  HomeLivingRoute: HomeLivingRoute,
  LearningWorkshopsRoute: LearningWorkshopsRoute,
  MeetingsConferenceEssentialsRoute: MeetingsConferenceEssentialsRoute,
  MilestoneGiftsRoute: MilestoneGiftsRoute,
  OfficeCarryEssentialsRoute: OfficeCarryEssentialsRoute,
  PhysicalFitnessKitRoute: PhysicalFitnessKitRoute,
  RewardsRecognitionRoute: RewardsRecognitionRoute,
  TechGiftsRoute: TechGiftsRoute,
  TrainingRoute: TrainingRoute,
  TravelRoute: TravelRoute,
  VipExecutiveGiftingRoute: VipExecutiveGiftingRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
